export const productList = [
  {
    ProductID: 7631,
    SKU: "HEH-9133",
    Name: "On Cloud Nine Pillow",
    ProductURL: "https://www.domain.com/product/heh-9133",
    Price: 24.99,
    RetailPrice: 24.99,
    ThumbnailURL: "https://www.domain.com/images/heh-9133_600x600.png",
    SearchKeywords: "lorem, ipsum, dolor, ...",
    Description: "Lobortis elementum nibh tellus molestie nunc non blandit massa. Imperdiet massa tincidunt nunc pulvinar sapien et. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Leo vel fringilla est ullamcorper. Leo integer malesuada nunc vel risus commodo viverra. Eget lorem dolor sed viverra ipsum nunc.",
    Category: "Home>Home Decor>Pillows|Back In Stock",
    CategoryID: "298|511",
    Brand: "FabDecor",
    ChildSKU: "",
    ChildPrice: "",
    Color: "White",
    ColorFamily: "White",
    ColorSwatches: "",
    Size: "",
    ShoeSize: "",
    PantsSize: "",
    Occassion: "",
    Season: "",
    Badges: "",
    RatingAvg: 4.2,
    RatingCount: 8,
    InventoryCount: 21,
    DateCreated: "2018-03-03 17:41:13",
  },
  {
    ProductID: 7615,
    SKU: "HEH-2245",
    Name: "Simply Sweet Blouse",
    ProductURL: "https://www.domain.com/product/heh-2245",
    Price: 42,
    RetailPrice: 59.95,
    ThumbnailURL: "https://www.domain.com/images/heh-2245_600x600.png",
    SearchKeywords: "lorem, ipsum, dolor, ...",
    Description: "Felis eget velit aliquet sagittis id consectetur purus ut. Convallis aenean et tortor at. Lacus suspendisse faucibus interdum posuere lorem ipsum. Enim diam vulputate ut pharetra sit amet aliquam id. Dapibus ultrices in iaculis nunc sed. Dolor sit amet consectetur adipiscing elit ut aliquam.",
    Category: "Clothing>Tops>Blouses|Clearance|Tops On Sale",
    CategoryID: "285|512|604",
    Brand: "Entity Apparel",
    ChildSKU:
      "HEH-2245-RSWD-SM|HEH-2245-RSWD-MD|HEH-2245-THGR-SM|EH-2245-THGR-MD|HEH-2245-DKCH-SM|HEH-2245-DKCH-MD",
    ChildPrice: "42|59.99",
    Color: "Rosewood|Thyme Green|Dark Charcoal",
    ColorFamily: "Red|Green|Grey",
    ColorSwatches:
      '[{"color":"Rosewood", "family":"Red", "swatch_hex":"#65000b", "thumbnail":"/images/heh-2245-rswd-sm_600x600.png", "price":42}, {"color":"Thyme Green", "family":"Green", "swatch_img":"/swatches/thyme_green.png", "thumbnail":"/images/heh-2245-thgr-sm_600x600.png", "price":59.99}, {"color":"Dark Charcoal", "family":"Grey", "swatch_hex":"#36454f", "thumbnail":"/images/heh-2245-dkch-sm_600x600.png", "price":59.99}]',
    Size: "Small|Medium",
    ShoeSize: "",
    PantsSize: "",
    Occassion: "",
    Season: "Summer|Spring",
    Badges: "Exclusive|Clearance",
    RatingAvg: 4.5,
    RatingCount: 10,
    InventoryCount: 8,
    DateCreated: "2018-03-20 22:24:21",
  },
  {
    ProductID: 8100,
    SKU: "WKS-6016",
    Name: "Uptown Girl Blouse",
    ProductURL: "https://www.domain.com/product/wks-6016",
    Price: 58,
    RetailPrice: 89.95,
    ThumbnailURL: "https://www.domain.com/images/wks-6016_600x600.png",
    SearchKeywords: "lorem, ipsum, dolor, ...",
    Description: "Ut tellus elementum sagittis vitae. Cursus mattis molestie a iaculis at. Nibh sit amet commodo nulla facilisi. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Vitae elementum curabitur vitae nunc sed velit dignissim. In cursus turpis massa tincidunt dui ut ornare lectus sit.",
    Category: "Clothing>Tops>Blouses",
    CategoryID: 285,
    Brand: "Entity Apparel",
    ChildSKU: "WKS-6016-CORD-MD|WKS-6016-KEGR-MD",
    ChildPrice: "",
    Color: "Coral Red|Kelly Green",
    ColorFamily: "Red|Green",
    ColorSwatches:
      '[{"color":"Coral Red", "family":"Red", "swatch_img":"/swatches/coral_red.png", "thumbnail":"/images/wks-6016-cord-md_600x600.png", "price":58}, {"color":"Kelly Green", "family":"Green", "swatch_img":"/swatches/kelly_green.png", "thumbnail":"/images/wks-6016-kegr-md_600x600.png", "price":58}]',
    Size: "Medium",
    ShoeSize: "",
    PantsSize: "",
    Occassion: "",
    Season: "Summer|Spring",
    Badges: "Exclusive",
    RatingAvg: 4.2,
    RatingCount: 11,
    InventoryCount: 9,
    DateCreated: "2018-03-16 21:55:28",
  },
  {
    ProductID: 6489,
    SKU: "DKO-PROF",
    Name: "Knock Your Socks Off Lace-Up Heels",
    ProductURL: "https://www.domain.com/product/dko-prof",
    Price: 38,
    RetailPrice: 60,
    ThumbnailURL: "https://www.domain.com/images/dko-prof_600x600.png",
    SearchKeywords: "lorem, ipsum, dolor, ...",
    Description: "Risus in hendrerit gravida rutrum quisque. Condimentum id venenatis a condimentum vitae sapien pellentesque. Scelerisque eu ultrices vitae auctor eu. Arcu odio ut sem nulla pharetra diam sit amet. Congue eu consequat ac felis. Diam sit amet nisl suscipit. Sit amet nisl purus in mollis nunc sed id. Massa tincidunt dui ut ornare lectus sit.",
    Category: "Shoes>Heels>Lace-Up Heels|Featured Products|Shoes On Sale",
    CategoryID: "310|719|605",
    Brand: "Spark Collective",
    ChildSKU:
      "DKO-PROF-BLK-5|DKO-PROF-BLK-5.5|DKO-PROF-BLK-6|DKO-PROF-BLK-7|DKO-PROF-BLK-7.5",
    ChildPrice: "",
    Color: "Black",
    ColorFamily: "Black",
    ColorSwatches: "",
    Size: "",
    ShoeSize: "5|5.5|6|7|7.5",
    PantsSize: "",
    Occassion: "",
    Season: "",
    Badges: "Featured",
    RatingAvg: 4.9,
    RatingCount: 4,
    InventoryCount: 19,
    DateCreated: "2018-02-28 23:37:28",
  },
  {
    ProductID: 7732,
    SKU: "HEH-2172",
    Name: "My Cup of Tea Sweater",
    ProductURL: "https://www.domain.com/product/heh-2172",
    Price: 68,
    RetailPrice: 68,
    ThumbnailURL: "https://www.domain.com/images/heh-2172_600x600.png",
    SearchKeywords: "lorem, ipsum, dolor, ...",
    Description: "Natoque penatibus et magnis dis parturient montes nascetur. Nibh mauris cursus mattis molestie a iaculis. Sit amet consectetur adipiscing elit duis tristique sollicitudin. Blandit massa enim nec dui nunc. Justo donec enim diam vulputate ut. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Iaculis eu non diam phasellus vestibulum lorem sed risus.",
    Category: "Clothing>Tops>Sweaters",
    CategoryID: 277,
    Brand: "Enigma Clothes",
    ChildSKU: "HEH-2172-WHT-MD|HEH-2172-WHT-LG",
    ChildPrice: "",
    Color: "White",
    ColorFamily: "White",
    ColorSwatches: "",
    Size: "Medium|Large",
    ShoeSize: "",
    PantsSize: "",
    Occassion: "",
    Season: "Winter",
    Badges: "",
    RatingAvg: 4.6,
    RatingCount: 22,
    InventoryCount: 3,
    DateCreated: "2018-03-01 20:18:20",
  },
  {
    ProductID: 7609,
    SKU: "HEH-2211",
    Name: "Walk On Out Slip On Sneakers",
    ProductURL: "https://www.domain.com/product/heh-2211",
    Price: 34.99,
    RetailPrice: 34.99,
    ThumbnailURL: "https://www.domain.com/images/heh-2211_600x600.png",
    SearchKeywords: "lorem, ipsum, dolor, ...",
    Description: "Aliquam etiam erat velit scelerisque in. Leo vel fringilla est ullamcorper. Leo integer malesuada nunc vel risus commodo viverra. Eget lorem dolor sed viverra ipsum nunc. Aliquam ut porttitor leo a diam sollicitudin tempor.",
    Category: "Shoes>Sneakers>Slip-On Sneakers",
    CategoryID: 302,
    Brand: "Temptation",
    ChildSKU:
      "HEH-2211-BSQ-6|HEH-2211-BSQ-7|HEH-2211-BSQ-8|HEH-2211-BSQ-9|HEH-2211-BSQ-10|HEH-2211-BSQ-10.5",
    ChildPrice: "",
    Color: "Bisque",
    ColorFamily: "Beige",
    ColorSwatches: "",
    Size: "",
    ShoeSize: "6|7|8|9|10|10.5",
    PantsSize: "",
    Occassion: "",
    Season: "",
    Badges: "",
    RatingAvg: 3.9,
    RatingCount: 5,
    InventoryCount: 2,
    DateCreated: "2018-03-20 22:15:34",
  },
  {
    ProductID: 7675,
    SKU: "DKO-CAMEL",
    Name: "Warm Hearts Sweater",
    ProductURL: "https://www.domain.com/product/dko-camel",
    Price: 54.49,
    RetailPrice: 54.49,
    ThumbnailURL: "https://www.domain.com/images/dko-camel_600x600.png",
    SearchKeywords: "lorem, ipsum, dolor, ...",
    Description: "Proin sagittis nisl rhoncus mattis rhoncus urna neque. Facilisis sed odio morbi quis commodo odio aenean sed adipiscing. Velit dignissim sodales ut eu sem integer vitae justo. Adipiscing diam donec adipiscing tristique risus nec. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium.",
    Category: "Clothing>Tops>Sweaters|Back In Stock|Featured Products",
    CategoryID: "277|511|719",
    Brand: "Legacy Apparel",
    ChildSKU: "DKO-CAMEL-GRY-SM",
    ChildPrice: "",
    Color: "Grey",
    ColorFamily: "Grey",
    ColorSwatches: "",
    Size: "Small",
    ShoeSize: "",
    PantsSize: "",
    Occassion: "",
    Season: "Winter",
    Badges: "Featured|Free Shipping",
    RatingAvg: 5,
    RatingCount: 2,
    InventoryCount: 20,
    DateCreated: "2018-03-19 20:53:04",
  },
  {
    ProductID: 7463,
    SKU: "WKS-5026",
    Name: "Silver Lining Dress",
    ProductURL: "https://www.domain.com/product/wks-5026",
    Price: 62,
    RetailPrice: 62,
    ThumbnailURL: "https://www.domain.com/images/wks-5026_600x600.png",
    SearchKeywords: "lorem, ipsum, dolor, ...",
    Description: "Elit duis tristique sollicitudin nibh. Vitae suscipit tellus mauris a diam. Lorem dolor sed viverra ipsum nunc aliquet bibendum. Enim diam vulputate ut pharetra sit amet aliquam id. Dapibus ultrices in iaculis nunc sed.",
    Category: "Dresses>Formal Dresses|All Dresses",
    CategoryID: "220|201",
    Brand: "Temptation",
    ChildSKU: "WKS-5026-GRNP-XS|WKS-5026-GRNP-SM|WKS-5026-GRNP-MD",
    ChildPrice: "",
    Color: "Green Print",
    ColorFamily: "Green",
    ColorSwatches: "",
    Size: "X-Small|Small|Medium",
    ShoeSize: "",
    PantsSize: "",
    Occassion: "Formal",
    Season: "",
    Badges: "",
    RatingAvg: 5,
    RatingCount: 9,
    InventoryCount: 0,
    DateCreated: "2018-03-01 19:59:05",
  },
  {
    ProductID: 7677,
    SKU: "PCH-8738",
    Name: "Follow The Beat Sneakers",
    ProductURL: "https://www.domain.com/product/pch-8738",
    Price: 32,
    RetailPrice: 32,
    ThumbnailURL: "https://www.domain.com/images/pch-8738_600x600.png",
    SearchKeywords: "lorem, ipsum, dolor, ...",
    Description: "Dolor sit amet consectetur adipiscing elit ut aliquam. Quis vel eros donec ac. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Vitae elementum curabitur vitae nunc sed velit dignissim.",
    Category: "Shoes>Sneakers>Slip-On Sneakers",
    CategoryID: 302,
    Brand: "Fusion Fashion",
    ChildSKU:
      "PCH-8738-GRY-8|PCH-8738-GRY-9|PCH-8738-BLK-8|PCH-8738-BLK-9|PCH-8738-LEP-8|PCH-8738-LEP-9",
    ChildPrice: "",
    Color: "Grey|Black|Leopard",
    ColorFamily: "Grey|Black|Multi",
    ColorSwatches:
      '[{"color":"Grey", "family":"Grey", "swatch_hex":"#d3d3d3", "thumbnail":"/images/pch-8738-gry-8_600x600.png", "price":32}, {"color":"Black", "family":"Black", "swatch_hex":"#000000", "thumbnail":"/images/pch-8738-blk-8_600x600.png", "price":32}, {"color":"Leopard", "family":["Black","Multi"], "swatch_img":"/swatches/leopard.png", "thumbnail":"/images/pch-8738-lep-8_600x600.png", "price":32}]',
    Size: "",
    ShoeSize: "8|9",
    PantsSize: "",
    Occassion: "",
    Season: "",
    Badges: "",
    RatingAvg: 4.5,
    RatingCount: 1,
    InventoryCount: 8,
    DateCreated: "2019-01-31 16:24:09",
  },
  {
    ProductID: 8099,
    SKU: "PCH-8475",
    Name: "Cup of Joe Pillow",
    ProductURL: "https://www.domain.com/product/pch-8475",
    Price: 36,
    RetailPrice: 36,
    ThumbnailURL: "https://www.domain.com/images/pch-8475_600x600.png",
    SearchKeywords: "lorem, ipsum, dolor, ...",
    Description: "In cursus turpis massa tincidunt dui ut ornare lectus sit. Diam donec adipiscing tristique risus nec. Et malesuada fames ac turpis egestas maecenas pharetra.",
    Category: "Home>Home Decor>Pillows",
    CategoryID: 298,
    Brand: "FabDecor",
    ChildSKU: "",
    ChildPrice: "",
    Color: "Seafoam Green",
    ColorFamily: "Green",
    ColorSwatches: "",
    Size: "",
    ShoeSize: "",
    PantsSize: "",
    Occassion: "",
    Season: "",
    Badges: "",
    RatingAvg: 4,
    RatingCount: 1,
    InventoryCount: 18,
    DateCreated: "2018-02-28 19:03:26",
  },
  {
    ProductID: 7425,
    SKU: "BCO-SK101",
    Name: "Burst Your Bubble Denim Jacket",
    ProductURL: "https://www.domain.com/product/bco-sk101",
    Price: 84,
    RetailPrice: 110,
    ThumbnailURL: "https://www.domain.com/images/bco-sk101_600x600.png",
    SearchKeywords: "lorem, ipsum, dolor, ...",
    Description: "Amet cursus sit amet dictum sit amet justo donec enim. Sit amet consectetur adipiscing elit ut aliquam. Feugiat scelerisque varius morbi enim.",
    Category: "Clothing>Tops>Jackets|Clearance|Tops On Sale",
    CategoryID: "279|512|604",
    Brand: "Zigzag Clothing",
    ChildSKU: "BCO-SK101-WSDM-LG",
    ChildPrice: "",
    Color: "Washed Denim",
    ColorFamily: "Denim",
    ColorSwatches: "",
    Size: "Large",
    ShoeSize: "",
    PantsSize: "",
    Occassion: "",
    Season: "",
    Badges: "Clearance",
    RatingAvg: 5,
    RatingCount: 1,
    InventoryCount: 17,
    DateCreated: "2018-05-04 21:32:28",
  },
  {
    ProductID: 8102,
    SKU: "HEH-2254",
    Name: "Walk It Out Heels",
    ProductURL: "https://www.domain.com/product/heh-2254",
    Price: 32,
    RetailPrice: 32,
    ThumbnailURL: "https://www.domain.com/images/heh-2254_600x600.png",
    SearchKeywords: "lorem, ipsum, dolor, ...",
    Description: "Maecenas accumsan lacus vel facilisis. Viverra adipiscing at in tellus integer feugiat. Arcu odio ut sem nulla pharetra diam sit amet. Congue eu consequat ac felis. Diam sit amet nisl suscipit. ",
    Category: "Shoes>Heels>Pumps|New Arrivals|Featured Products",
    CategoryID: "311|510|719",
    Brand: "Fusion Fashion",
    ChildSKU: "HEH-2254-BLK-6|HEH-2254-BLK-7|HEH-2254-BLK-8",
    ChildPrice: "",
    Color: "Black",
    ColorFamily: "Black",
    ColorSwatches: "",
    Size: "",
    ShoeSize: "6|7|8",
    PantsSize: "",
    Occassion: "",
    Season: "",
    Badges: "Featured",
    RatingAvg: 4.7,
    RatingCount: 5,
    InventoryCount: 10,
    DateCreated: "2019-01-31 16:48:23",
  },
  {
    ProductID: 9964,
    SKU: "BCO-2208",
    Name: "Word To The Wise Journal",
    ProductURL: "https://www.domain.com/product/bco-2208",
    Price: 14.95,
    RetailPrice: 14.95,
    ThumbnailURL: "https://www.domain.com/images/bco-2208_600x600.png",
    SearchKeywords: "lorem, ipsum, dolor, ...",
    Description: "Sit amet nisl purus in mollis nunc sed id. Massa tincidunt dui ut ornare lectus sit. Sed cras ornare arcu dui vivamus. Volutpat sed cras ornare arcu dui vivamus arcu. Eget mauris pharetra et ultrices neque ornare.",
    Category: "Home>Desk Decor>Journals",
    CategoryID: 410,
    Brand: "Vintage Home",
    ChildSKU: "",
    ChildPrice: "",
    Color: "Blue",
    ColorFamily: "Blue",
    ColorSwatches: "",
    Size: "",
    ShoeSize: "",
    PantsSize: "",
    Occassion: "",
    Season: "",
    Badges: "",
    RatingAvg: 4,
    RatingCount: 32,
    InventoryCount: 5,
    DateCreated: "2018-10-18 15:19:37",
  },
  {
    ProductID: 10440,
    SKU: "KOI-721",
    Name: "Basic Beauty Off-The-Shoulder Dress",
    ProductURL: "https://www.domain.com/product/koi-721",
    Price: 52,
    RetailPrice: 78,
    ThumbnailURL: "https://www.domain.com/images/koi-721_600x600.png",
    SearchKeywords: "lorem, ipsum, dolor, ...",
    Description: "Ultricies mi quis hendrerit dolor magna. Amet est placerat in egestas. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Enim sed faucibus turpis in eu. Vestibulum morbi blandit cursus risus.",
    Category: "Dresses>Off-The-Shoulder Dresses|Dresses On Sale",
    CategoryID: "221|603",
    Brand: "Oasis",
    ChildSKU: "KOI-721-BLP-SM|KOI-721-BLP-MD",
    ChildPrice: "",
    Color: "Blue Print",
    ColorFamily: "Blue|Multi",
    ColorSwatches: "",
    Size: "Small|Medium",
    ShoeSize: "",
    PantsSize: "",
    Occassion: "Graduation",
    Season: "",
    Badges: "Exclusive",
    RatingAvg: 3.2,
    RatingCount: 15,
    InventoryCount: 30,
    DateCreated: "2018-03-03 17:38:50",
  },
  {
    ProductID: 6060,
    SKU: "VBH-V5102",
    Name: "Sunset Boulevard Pants",
    ProductURL: "https://www.domain.com/product/vbh-v5102",
    Price: 44,
    RetailPrice: 60,
    ThumbnailURL: "https://www.domain.com/images/vbh-v5102_600x600.png",
    SearchKeywords: "lorem, ipsum, dolor, ...",
    Description: "Dolor sit amet consectetur adipiscing elit pellentesque. Lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor. Cursus euismod quis viverra nibh cras pulvinar.",
    Category: "Clothing>Bottoms>Pants|All Bottoms",
    CategoryID: "236|204",
    Brand: "Monolith",
    ChildSKU:
      "VBH-V5102-WHT-24|VBH-V5102-WHT-25|VBH-V5102-WHT-26|VBH-V5102-WHT-27|VBH-V5102-BEG-24|VBH-V5102-BEG-25|VBH-V5102-BEG-26|VBH-V5102-BEG-27|VBH-V5102-BEG-30|VBH-V5102-BEG-31",
    ChildPrice: "",
    Color: "White|Beige",
    ColorFamily: "White|Beige",
    ColorSwatches:
      '[{"color":"White", "family":"White", "swatch_hex":"#ffffff", "thumbnail":"/images/vbh-v5102-wht-24_600x600.png", "price":44}, {"color":"Beige", "family":"Beige", "swatch_hex":"#f5f5dc", "thumbnail":"/images/vbh-v5102-bge-24_600x600.png", "price":44}]',
    Size: "",
    ShoeSize: "",
    PantsSize: "24|25|26|27|30|31",
    Occassion: "",
    Season: "",
    Badges: "",
    RatingAvg: 3.8,
    RatingCount: 33,
    InventoryCount: 1,
    DateCreated: "2018-02-28 23:57:53",
  },
  {
    ProductID: 10448,
    SKU: "SKE-15460",
    Name: "Across The Pond Boots",
    ProductURL: "https://www.domain.com/product/ske-15460",
    Price: 74.49,
    RetailPrice: 74.49,
    ThumbnailURL: "https://www.domain.com/images/ske-15460_600x600.png",
    SearchKeywords: "lorem, ipsum, dolor, ...",
    Description: "Tristique risus nec feugiat in fermentum posuere urna nec. Sit amet porttitor eget dolor morbi non. Porta non pulvinar neque laoreet suspendisse interdum consectetur. Justo donec enim diam vulputate ut. ",
    Category: "Shoes>Boots>Flat Boots",
    CategoryID: 334,
    Brand: "Legacy Collective",
    ChildSKU: "SKE-15460-BRN-6|SKE-15460-BRN-7|SKE-15460-BRN-8.5",
    ChildPrice: "",
    Color: "Brown",
    ColorFamily: "Brown",
    ColorSwatches: "",
    Size: "",
    ShoeSize: "6|7|8.5",
    PantsSize: "",
    Occassion: "",
    Season: "",
    Badges: "",
    RatingAvg: 5,
    RatingCount: 6,
    InventoryCount: 0,
    DateCreated: "2018-06-25 18:09:07",
  },
  {
    ProductID: 8137,
    SKU: "PCH-8705",
    Name: "Once Upon A Time Lace Dress",
    ProductURL: "https://www.domain.com/product/pch-8705",
    Price: 50,
    RetailPrice: 108,
    ThumbnailURL: "https://www.domain.com/images/pch-8705_600x600.png",
    SearchKeywords: "lorem, ipsum, dolor, ...",
    Description: "Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Iaculis eu non diam phasellus vestibulum lorem sed risus. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida.",
    Category: "Dresses>Lace Dresses|Dresses>All Dresses|New Arrivals",
    CategoryID: "222|201|510",
    Brand: "Oasis",
    ChildSKU:
      "PCH-8705-WHT-SM|PCH-8705-WHT-MD|PCH-8705-WHT-LG|PCH-8705-BLK-SM|PCH-8705-BLK-MD|PCH-8705-BLK-LG|PCH-8705-LTBL-SM|PCH-8705-LTBL-MD|PCH-8705-LTBL-LG",
    ChildPrice: "50|72|108",
    Color: "White|Black|Light Blue",
    ColorFamily: "White|Black|Blue",
    ColorSwatches:
      '[{"color":"White", "family":"White", "swatch_hex":"#ffffff", "thumbnail":"/images/pch-8705-wht-sm_600x600.png", "price":50}, {"color":"Black", "family":"Black", "swatch_hex":"#000000", "thumbnail":"/images/pch-8705-blk-sm_600x600.png", "price":108}, {"color":"Light Blue", "family":"Blue", "swatch_img":"/swatches/light_blue.png", "thumbnail":"/images/pch-8705-ltbl-sm_600x600.png", "price":72}]',
    Size: "Small|Medium|Large",
    ShoeSize: "",
    PantsSize: "",
    Occassion: "Party",
    Season: "",
    Badges: "",
    RatingAvg: 5,
    RatingCount: 4,
    InventoryCount: 0,
    DateCreated: "2019-02-15 20:33:28",
  },
  {
    ProductID: 10018,
    SKU: "PGF-ESS",
    Name: "Lovey Dovey Maxi Dress",
    ProductURL: "https://www.domain.com/product/pgf-ess",
    Price: 68,
    RetailPrice: 68,
    ThumbnailURL: "https://www.domain.com/images/pgf-ess_600x600.png",
    SearchKeywords: "lorem, ipsum, dolor, ...",
    Description: "Eros in cursus turpis massa tincidunt dui ut ornare lectus. Tempus imperdiet nulla malesuada pellentesque elit eget. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper. ",
    Category: "Dresses>Maxi Dresses|Dresses>All Dresses|New Arrivals",
    CategoryID: "223|201|510",
    Brand: "Oasis",
    ChildSKU:
      "PGF-ESS-FUOR-SM|PGF-ESS-FUOR-MD|PGF-ESS-FUOR-LG|PGF-ESS-PRPT-SM|PGF-ESS-PRPT-MD|PGF-ESS-PRPT-LG",
    ChildPrice: "",
    Color: "Fuschia Orange|Perfect Petals|Island Time",
    ColorFamily: "Orange|Pink|Yellow|Multi",
    ColorSwatches:
      '[{"color":"Fuschia Orange", "family":["Orange","Pink"], "swatch_img":"/swatches/fuschia_orange.png", "thumbnail":"/images/pgf-ess-fuor-sm_600x600.png", "price":68}, {"color":"Perfect Petals", "family":"Pink", "swatch_img":"/swatches/perfect_petals.png", "thumbnail":"/images/pgf-ess-prpt-sm_600x600.png", "price":68}, {"color":"Island Time", "family":["Yellow","Orange","Multi"], "swatch_img":"/swatches/island_time.png", "thumbnail":"/images/pgf-ess-istm-sm_600x600.png", "price":68}]',
    Size: "Small|Medium|Large",
    ShoeSize: "",
    PantsSize: "",
    Occassion: "Party",
    Season: "",
    Badges: "",
    RatingAvg: 4.8,
    RatingCount: 12,
    InventoryCount: 24,
    DateCreated: "2019-02-20 21:38:02",
  },
  {
    ProductID: 5670,
    SKU: "HEH-2223",
    Name: "Shot in the Dark Pillow",
    ProductURL: "https://www.domain.com/product/heh-2223",
    Price: 40,
    RetailPrice: 40,
    ThumbnailURL: "https://www.domain.com/images/heh-2223_600x600.png",
    SearchKeywords: "lorem, ipsum, dolor, ...",
    Description: "Magna ac placerat vestibulum lectus mauris ultrices eros. Eget lorem dolor sed viverra ipsum nunc aliquet. At volutpat diam ut venenatis tellus in.",
    Category: "Home>Home Decor>Pillows",
    CategoryID: 298,
    Brand: "Vintage Home",
    ChildSKU: "",
    ChildPrice: "",
    Color: "Coral",
    ColorFamily: "Red",
    ColorSwatches: "",
    Size: "",
    ShoeSize: "",
    PantsSize: "",
    Occassion: "",
    Season: "",
    Badges: "Free Shipping",
    RatingAvg: 4,
    RatingCount: 3,
    InventoryCount: 8,
    DateCreated: "2018-03-01 20:28:28",
  },
  {
    ProductID: 9020,
    SKU: "PGF-RIK",
    Name: "Diamonds Are Forever Pillow",
    ProductURL: "https://www.domain.com/product/pgf-rik",
    Price: 36,
    RetailPrice: 36,
    ThumbnailURL: "https://www.domain.com/images/pgf-rik_600x600.png",
    SearchKeywords: "lorem, ipsum, dolor, ...",
    Description: "Scelerisque eu ultrices vitae auctor eu. Natoque penatibus et magnis dis parturient montes nascetur. Nibh mauris cursus mattis molestie a iaculis. Sit amet consectetur adipiscing elit duis tristique sollicitudin. Blandit massa enim nec dui nunc. Aliquam etiam erat velit scelerisque in.",
    Category: "Home>Home Decor>Pillows",
    CategoryID: 298,
    Brand: "Vintage Home",
    ChildSKU: "",
    ChildPrice: "",
    Color: "Light Blue",
    ColorFamily: "Blue",
    ColorSwatches: "",
    Size: "",
    ShoeSize: "",
    PantsSize: "",
    Occassion: "",
    Season: "",
    Badges: "Free Shipping",
    RatingAvg: 5,
    RatingCount: 3,
    InventoryCount: 11,
    DateCreated: "2018-03-16 22:17:50",
  },
];
